name: "Close stale PRs"
on:
  schedule:
  - cron: "0 0 * * *" # end of every day

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@5f858e3efba33a5ca4407a664cc011ad407f2008 # v10.1.0
      with:
        ascending: true
        operations-per-run: 100
        days-before-stale: 15
        days-before-close: 7
        exempt-all-assignees: true # anything with a assignee won't be closed
        stale-pr-message: "This PR is more than 2 weeks old. Please remove the
          stale label, update, or comment if this PR is still valid and
          relevant, otherwise it will be closed in 7 days."
